/**
 * Unit test: sanitizer against REAL server output (tests/unit/js/fixtures/render.json,
 * generated by tests/unit/php/render-fixtures.php with hostile values), plus
 * targeted mutation-XSS, DOM-clobbering and SVG cases.
 *
 * Browser: jsdom (a DOM model, not a real browser engine; see the Chromium test
 * for real-engine evidence). Run:
 *   NODE_PATH=/path/to/node_modules node tests/unit/js/safe-html-fixtures.test.cjs
 */
'use strict';

const fs = require('fs');
const path = require('path');
const assert = require('assert');
const { JSDOM } = require('jsdom');

const root = path.join(__dirname, '..', '..', '..');
const appSource = fs.readFileSync(path.join(root, 'pixva', 'assets', 'js', 'app.js'), 'utf8');
const fixtures = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'render.json'), 'utf8'));

const dom = new JSDOM('<!doctype html><html><body></body></html>', { runScripts: 'outside-only', url: 'https://example.test/' });
const { window } = dom;
window.PIXVA = { rest: '/wp-json/pixva/v1/', events: [], props: [] };
window.fetch = () => new Promise(() => {});
window.eval(appSource);
const pixva = window.pixva;
assert.strictEqual(typeof pixva.setSafeHTML, 'function');
assert.strictEqual(typeof pixva.setSafeFromNode, 'function');

let passed = 0;
let failed = 0;
function test(name, fn) {
	try {
		window.__xss = undefined;
		fn();
		passed += 1;
		console.log('ok   - ' + name);
	} catch (e) {
		failed += 1;
		console.log('FAIL - ' + name + '\n       ' + e.message);
	}
}

function render(html) {
	const host = window.document.createElement('div');
	window.document.body.appendChild(host);
	pixva.setSafeHTML(host, html);
	return host;
}

function violations(root) {
	const out = [];
	for (const el of [root].concat(Array.from(root.querySelectorAll('*')))) {
		for (const a of Array.from(el.attributes)) {
			const n = a.name.toLowerCase();
			const v = a.value.replace(/[\u0000-\u0020\u007f]/g, '');
			if (n.startsWith('on')) out.push('handler ' + n + ' on ' + el.localName);
			if (/^(javascript|vbscript|data):/i.test(v) && (n === 'href' || n === 'src' || n === 'xlink:href' || n === 'action' || n === 'formaction')) out.push('unsafe url ' + n);
			if (n === 'style' || n === 'srcset' || n === 'values' || n === 'target') out.push('forbidden attribute ' + n + ' on ' + el.localName);
		}
	}
	const banned = root.querySelectorAll('script,style,iframe,object,embed,form,button,input,noscript,template,base,link,meta,animate,set,foreignobject,use');
	if (banned.length) out.push('banned element ' + banned[0].localName);
	return out;
}

// --- Real PHP fixtures --------------------------------------------------------
for (const key of Object.keys(fixtures)) {
	test('real ' + key + ' fixture: no executable markup', () => {
		const host = render(fixtures[key]);
		assert.deepStrictEqual(violations(host), []);
		assert.strictEqual(window.__xss, undefined);
	});
}

test('hostile order text is shown as text, not parsed as markup', () => {
	const host = render(fixtures.order_view);
	assert.ok(host.textContent.indexOf('<img src=x onerror="alert(1)">') !== -1, 'escaped payload should appear as visible text');
	assert.strictEqual(host.querySelector('img'), null);
	assert.strictEqual(host.querySelector('script'), null);
});

test('real order view keeps its structure and accessible names', () => {
	const host = render(fixtures.order_view);
	const article = host.querySelector('article.order');
	assert.ok(article, 'article kept');
	assert.strictEqual(article.getAttribute('aria-labelledby'), 'order-PXV-ABC-123');
	assert.ok(host.querySelector('h2#order-PXV-ABC-123'), 'heading id kept');
	assert.ok(host.querySelector('li[aria-current="step"]'), 'current step kept');
	assert.ok(host.querySelector('details.order__history summary'), 'history disclosure kept');
});

test('a quote-injected datetime does not create an attribute', () => {
	const host = render(fixtures.order_view);
	const t = host.querySelector('time');
	assert.ok(t, 'time element kept');
	assert.strictEqual(host.querySelector('[onclick]'), null);
	assert.strictEqual(t.hasAttribute('onclick'), false);
});

test('real calc result keeps its tracking hook and price text', () => {
	const host = render(fixtures.calc_result);
	assert.ok(host.querySelector('[data-track-view="price_calculator_completed"]'));
	assert.ok(host.querySelector('p.price'));
});

// --- Mutation XSS and namespace confusion -----------------------------------
const mxss = {
	'form/math/style nesting': '<form><math><mtext></form><form><mglyph><style></math><img src=x onerror=window.__xss=1>',
	'svg foreignObject': '<svg><foreignObject><iframe src="javascript:window.__xss=1"></iframe></foreignObject></svg>',
	'svg animate values': '<svg><a><animate attributeName="href" values="javascript:window.__xss=1"/><text>x</text></a></svg>',
	'svg style breakout': '<svg></p><style><a id="</style><img src=1 onerror=window.__xss=1>"></svg>',
	'noscript attribute breakout': '<noscript><p title="</noscript><img src=x onerror=window.__xss=1>">x</p></noscript>',
	'img srcset': '<img src="https://ok.example/a.png" srcset="javascript:window.__xss=1 1x">',
	'entity-split scheme': '<a href="&#106;&#97;&#118;&#97;script:window.__xss=1">x</a>',
	'tab-split scheme': '<a href="java\tscript:window.__xss=1">x</a>',
	'uppercase event': '<DIV ONMOUSEOVER="window.__xss=1">x</DIV>',
};
for (const [name, payload] of Object.entries(mxss)) {
	test('blocks ' + name, () => {
		const host = render(payload);
		assert.deepStrictEqual(violations(host), []);
		assert.strictEqual(window.__xss, undefined, 'payload executed');
	});
}

// --- DOM clobbering -----------------------------------------------------------
test('reserved ids are dropped (DOM clobbering)', () => {
	const host = render('<div id="pixva"><span id="document">a</span><span id="location">b</span><span id="order-PXV-1">c</span></div>');
	assert.strictEqual(host.querySelector('#pixva'), null);
	assert.strictEqual(host.querySelector('#document'), null);
	assert.strictEqual(host.querySelector('#location'), null);
	assert.ok(host.querySelector('#order-PXV-1'), 'ordinary id kept');
});

test('ids with markup or spaces are dropped', () => {
	const host = render('<div id="a b"><span id="x&quot;onfocus=1">c</span></div>');
	assert.strictEqual(host.querySelector('[id]'), null);
});

// --- setSafeFromNode (lookup path, no serialise/re-parse) -----------------
test('setSafeFromNode sanitises a DOMParser node in place', () => {
	const doc = new window.DOMParser().parseFromString('<div data-error-results><p onclick="window.__xss=1">ok</p><script>window.__xss=1</script></div>', 'text/html');
	const src = doc.querySelector('[data-error-results]');
	const host = window.document.createElement('div');
	window.document.body.appendChild(host);
	pixva.setSafeFromNode(host, src);
	assert.deepStrictEqual(violations(host), []);
	assert.strictEqual(host.textContent, 'ok');
	assert.strictEqual(window.__xss, undefined);
});

test('setSafeHTML with null, undefined and numbers does not throw', () => {
	const host = render('<p>x</p>');
	pixva.setSafeHTML(host, null);
	assert.strictEqual(host.childNodes.length, 0);
	pixva.setSafeHTML(host, 42);
	assert.strictEqual(host.textContent, '42');
});

console.log('\n' + passed + ' passed, ' + failed + ' failed');
process.exit(failed ? 1 : 0);
