#!/usr/bin/env python3
"""PIXVA class inventory audit.

Lists CSS classes used by theme PHP templates / JS that have no selector in
the theme stylesheets (style.css, assets/css/app.css), and selectors in the
stylesheets that no template or script references (possible dead CSS).

Static heuristic: dynamic class names built from variables are reported via
their literal prefix (e.g. "notice--" from 'notice--' . $type); prefixes are
matched against selectors that start with them.

Usage: python3 tools/class_audit.py [theme_dir]
Exit code 1 when used classes are missing from CSS.
"""
import os
import re
import sys

THEME = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'pixva')
CSS_FILES = ['style.css', 'assets/css/app.css', 'assets/css/admin.css']
# Classes styled by WordPress core / block library or used purely as JS hooks.
IGNORE = {
    'screen-reader-text', 'no-js', 'js', 'alignwide', 'alignfull', 'alignleft', 'alignright', 'aligncenter',
    'wp-block-image', 'wp-caption', 'wp-caption-text', 'gallery-caption', 'sticky', 'bypostauthor',
    'menu-item', 'current-menu-item', 'current_page_item', 'sub-menu', 'children', 'page-numbers', 'current',
    'comment-reply-link', 'avatar', 'dots', 'next', 'prev', 'custom-logo', 'custom-logo-link',
    'skip-link', 'widget',
    # Structural wrappers / JS hooks that intentionally carry no own rules.
    'site-main', 'form', 'calc', 'pixel-test', 'hero__text', 'brand__img', 'brand__name', 'brand-card__logo',
    'lookup__panel', 'site-footer__contact', 'pixva-admin', 'result',
    # Section modifier passed as a PHP argument (pixva_section_open), not a literal class attr.
    'band--dark',
    # Generated by WordPress (body/admin-bar/list tables/wp_login_form/menus/block buttons).
    'admin-bar', 'column-pixva_status', 'current-menu-ancestor', 'login-password', 'login-remember',
    'login-username', 'wp-element-button', 'menu', 'comment-body', 'comment-meta', 'reply', 'says', 'fn', 'url',
    'comment-author', 'vcard', 'comment-metadata', 'comment-content', 'depth-1', 'even', 'odd', 'thread-even',
    'thread-odd', 'parent', 'comment', 'pingback', 'trackback', 'comment-respond', 'comment-reply-title',
    'comment-form', 'logged-in-as', 'comment-notes', 'required-field-message', 'required', 'form-submit',
    'comment-form-comment', 'comment-form-author', 'comment-form-email', 'comment-form-url', 'comment-form-cookies-consent',
    # wp-admin core UI classes (styled by WordPress admin CSS).
    'dashicons', 'description', 'form-table', 'large-text', 'regular-text', 'striped', 'widefat', 'wrap',
    'notice-error', 'notice-info', 'notice-success', 'notice-warning', 'button', 'button-primary', 'button-secondary',
    'submit', 'post-edit-link', 'nav-links', 'navigation', 'pagination', 'nav-previous', 'nav-next',
}
SKIP_DIRS = {'node_modules', 'vendor', '.git'}


def read(path):
    with open(path, encoding='utf-8') as fh:
        return fh.read()


def css_classes():
    found = set()
    for rel in CSS_FILES:
        src = re.sub(r'/\*.*?\*/', '', read(os.path.join(THEME, rel)), flags=re.S)
        # Only selector text (before "{"), not declarations (avoids "0.5rem" etc.).
        for block in re.findall(r'([^{}]+)\{', src):
            if block.strip().startswith('@'):
                continue
            found.update(re.findall(r'\.(-?[_a-zA-Z][\w-]*)', block))
    return found


def used_classes():
    full, prefixes = {}, {}

    def add(name, where, store):
        store.setdefault(name, set()).add(where)

    for root, dirs, files in os.walk(THEME):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fn in files:
            if not fn.endswith(('.php', '.js')):
                continue
            path = os.path.join(root, fn)
            rel = os.path.relpath(path, THEME)
            src = read(path)
            chunks = []
            # class="..." / class='...' attributes (may contain PHP).
            chunks += re.findall(r'class\s*=\s*"([^"]*)"', src)
            chunks += re.findall(r"class\s*=\s*'([^']*)'", src)
            # Template-tag args and PHP arrays: 'class' => '...'.
            chunks += re.findall(r"'class'\s*=>\s*'([^']*)'", src)
            # pixva_list( $items, 'class' ) and similar list helpers.
            chunks += re.findall(r"pixva_list\([^;\n]*?,\s*'([a-z][\w -]*)'\s*\)\s*;", src)
            if fn.endswith('.js'):
                chunks += re.findall(r"className\s*=\s*'([^']*)'", src)
                chunks += re.findall(r"classList\.(?:add|remove|toggle|contains)\(\s*'([^']+)'", src)
                chunks += re.findall(r"\bel\(\s*'[a-z0-9]+'\s*,\s*'([^']*)'", src)
                for sel in re.findall(r"(?:querySelector(?:All)?|closest|matches)\(\s*'([^']+)'", src):
                    for c in re.findall(r'\.(-?[_a-zA-Z][\w-]*)', sel):
                        add(c, rel, full)
            for chunk in chunks:
                if fn.endswith('.js') and ('.' in chunk or '[' in chunk or '#' in chunk):
                    # Selector string: pull ".class" tokens only.
                    for c in re.findall(r'\.(-?[_a-zA-Z][\w-]*)', chunk):
                        add(c, rel, full)
                    continue
                # Strip embedded PHP, keep literal tokens around it.
                literal = re.sub(r'<\?php.*?\?>', ' \x00 ', chunk, flags=re.S)
                for tok in literal.split():
                    if '\x00' in tok or tok.endswith(('-', '_')):
                        base = tok.replace('\x00', '')
                        if re.match(r'^[a-z][\w-]*[-_]$', base):
                            add(base, rel, prefixes)
                        continue
                    if re.match(r'^-?[_a-zA-Z][\w-]*$', tok):
                        add(tok, rel, full)
            # PHP concatenation: 'prefix--' . $var
            for line in src.splitlines():
                if 'class' not in line:
                    continue
                for p in re.findall(r"([a-z][\w-]*(?:--|__|-))'\s*\.\s*(?:\$|esc_attr|sanitize)", line):
                    add(p, rel, prefixes)
    return full, prefixes


def main():
    css = css_classes()
    full, prefixes = used_classes()
    missing = sorted(c for c in full if c not in css and c not in IGNORE and not c.startswith(('wp-', 'pixva-meta', 'js-')))
    # 'route-' is a body-class hook; 'f-' is pixva_field()'s id prefix (same line as 'class').
    missing_prefix = sorted(p for p in prefixes if p not in ('route-', 'f-') and not any(c.startswith(p) for c in css))
    used_all = set(full)
    dead = sorted(c for c in css if c not in used_all and not any(c.startswith(p) for p in prefixes) and c not in IGNORE)
    print('CSS classes: %d | used literal: %d | used prefixes: %d' % (len(css), len(full), len(prefixes)))
    print('\nUsed but not styled (%d):' % len(missing))
    for c in missing:
        print('  %-32s %s' % (c, ', '.join(sorted(full[c])[:4])))
    print('\nDynamic prefixes with no styled variant (%d):' % len(missing_prefix))
    for p in missing_prefix:
        print('  %-32s %s' % (p, ', '.join(sorted(prefixes[p])[:4])))
    print('\nStyled but never referenced (%d):' % len(dead))
    print('  ' + ' '.join(dead))
    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
